import html2pdf from 'html2pdf.js'

export const exportTabAsPDF = async (elementId, filename) => {
  const element = document.getElementById(elementId)
  if (!element) return
  const opt = {
    margin: 10,
    filename: `${filename}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, backgroundColor: '#12121a' },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
  }
  await html2pdf().set(opt).from(element).save()
}

export const exportFullDesignAsPDF = async (designTitle) => {
  const tabs = [
    'hld-tab',
    'lld-tab',
    'database-tab',
    'api-tab',
    'uiux-tab',
    'scalability-tab',
  ]
  const combined = document.createElement('div')
  combined.style.backgroundColor = '#12121a'
  combined.style.color = '#f1f5f9'
  tabs.forEach((tabId) => {
    const el = document.getElementById(tabId)
    if (el) {
      const clone = el.cloneNode(true)
      clone.style.pageBreakAfter = 'always'
      combined.appendChild(clone)
    }
  })
  document.body.appendChild(combined)
  await html2pdf()
    .set({
      filename: `${designTitle}-blueprint.pdf`,
      margin: 10,
      html2canvas: { scale: 2 },
      jsPDF: { format: 'a4' },
    })
    .from(combined)
    .save()
  document.body.removeChild(combined)
}

export const generateOpenAPIYAML = (design) => {
  if (!design?.lld?.services) return ''
  let yaml = `openapi: 3.0.0\ninfo:\n  title: ${design.title || 'API'}\n  version: 1.0.0\npaths:\n`
  design.lld.services.forEach((service) => {
    service.endpoints?.forEach((ep) => {
      yaml += `  ${ep.path}:\n    ${ep.method.toLowerCase()}:\n      summary: ${ep.description}\n      tags:\n        - ${service.name}\n`
      if (ep.auth) yaml += `      security:\n        - bearerAuth: []\n`
      if (ep.requestBody && Object.keys(ep.requestBody).length > 0) {
        yaml += `      requestBody:\n        content:\n          application/json:\n            schema:\n              type: object\n`
      }
      yaml += `      responses:\n        '200':\n          description: Success\n`
    })
  })
  yaml += `components:\n  securitySchemes:\n    bearerAuth:\n      type: http\n      scheme: bearer\n`
  return yaml
}

export const generateSQLSchema = (design) => {
  if (!design?.database?.tables) return ''
  let sql = `-- ${design.title} Database Schema\n-- Generated by ArchMind\n\n`
  design.database.tables.forEach((table) => {
    sql += `CREATE TABLE ${table.name} (\n`
    table.columns?.forEach((col, i) => {
      const constraints = col.constraints?.join(' ') || ''
      sql += `  ${col.name} ${col.type} ${constraints}${
        i < table.columns.length - 1 ? ',' : ''
      }\n`
    })
    sql += `);\n\n`
    table.indexes?.forEach((idx) => {
      sql += `-- ${idx}\n`
    })
    sql += `\n`
  })
  return sql
}
